version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meusdesafios-db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: meusdesafios
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: meusdesafios_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: meusdesafios-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  postgres_data: